#!/usr/bin/env node
const ssh = require("../../common/ssh");

const firewall = args => {
  ssh.execute(`sh /jffs/scripts/firewall ${args.join(" ")}`);
};

module.exports = {
  run: firewall,
  helpname: "firewall [args]",
  description: "Opens the Skynet firewall with the passes args (optional)"
};
