language: node_js
node_js:
  - "10"
before_script:
  - npm run format
  - npm run lint
  - npm pack
after_success:
  - npm run coveralls
before_deploy:
  - tar -zcf coverage.tar.tgz coverage
deploy:
  - provider: releases
    api_key: $api_key
    file_glob: true
    file: "**/*.tgz"
    skip_cleanup: true
    draft: true
    name: $TRAVIS_BRANCH
    body: $TRAVIS_COMMIT_MESSAGE
    on:
      tags: true
