#!/usr/bin/env node
const ssh = require("../../common/ssh");

const commands = () => {
  ssh.execute(["ls -1 /usr/bin/ | grep -v '^d'"]);
};

module.exports = {
  run: commands,
  description: "Lists files in /usr/bin"
};
