#!/usr/bin/env node
const ssh = require("../common/ssh");

const terminal = args => {
  ssh.execute(args);
};

module.exports = {
  run: terminal,
  helpname: "terminal [args]",
  description: "Opens an ssh connection to the router and executes the args (optional)"
};
