/** Declaration file generated by dts-gen */

export = ssh_keygen;

declare namespace ssh_keygen {
  interface KeyGenOptions {
    location: string;
    comment?: string;
    password?: string;
    read?: boolean;
    force?: boolean;
    destroy?: boolean;
  }

  interface KeyGenCreationData {
    key: string;
    pubKey: string;
  }

  type KeyGenCallback = (err?: any, out?: KeyGenCreationData) => void;
}

declare function ssh_keygen(
  opts: ssh_keygen.KeyGenOptions,
  callback: ssh_keygen.KeyGenCallback
): void;
