/** Declaration file generated by dts-gen */

export = ssh_keygen;

declare interface KeyGenOptions {
  location: string;
  comment?: string;
  password?: string;
  read?: boolean;
  force?: boolean;
  destroy?: boolean;
}

declare interface KeyGenCreationData {
  key: string;
  pubKey: string;
}

declare type KeyGenCallback = (err?: any, out?: KeyGenCreationData) => void;

declare function ssh_keygen(
  opts: KeyGenOptions,
  callback: KeyGenCallback
): void;
