/** Declaration file generated by dts-gen */

export = ssh_agent;

declare interface SshIdentity {
  type: string;
  ssh_key: string;
  comment: string;
}

declare type RequestIdentitiesCallback = (
  err?: Error,
  keys?: SshIdentity[]
) => void;
declare type SignCallback = (err?: Error, signature?: string) => void;

declare class ssh_agent {
  constructor(options?: { timeout?: number });

  requestIdentities(callback: RequestIdentitiesCallback): any;

  sign(key: SshIdentity, data: any, callback: SignCallback): any;
}
