#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  if ! type "brew" > /dev/null; then
    echo "==> Installing Homebrew…"
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install
  fi
  
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi