#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

curl -sSL "https://git.io/dependency-installer.sh" | bash
