#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

install_dir="${HOME}/.router"
config="$install_dir/ssh/.ssh.config"
config_backup=""

set -e

cd "$(dirname "$0")/.."

script/bootstrap

symlink="/usr/local/bin/router"

if [ -f "$config" ]; then
    echo "==> Backing up existing configuration…"
    config_backup="$(mktemp)"
    cp "$config" "$config_backup"
fi

echo "==> Removing previous installation files…"

if [ -f "$symlink" ]; then rm -rf "$symlink"; fi
if [ -d "$install_dir" ]; then rm -rf "$install_dir"; fi

echo "==> Copying files…"
mkdir "$install_dir"
cp router.sh "$install_dir"
cp -R commands "$install_dir"
cp -R utils "$install_dir"
cp -R ssh "$install_dir"
chmod +x "$install_dir/router.sh"
ln -s "$install_dir/router.sh" $symlink

if [ -f "$config_backup" ]; then
    cp "$config_backup" "$config"
    rm "$config_backup"
fi

if [ ! -f "$config" ] 2>/dev/null; then
    "$install_dir/commands/router-writeconf.sh"
fi

echo "Setup done"
