#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

readonly SETUP_PATH="$(
  cd "$(dirname "$0")/.."
  pwd -P
)"

readonly TARGET_DIR="${HOME}/.router"
readonly SSH_CONFIG="$TARGET_DIR/ssh/.ssh.config"
readonly COMMAND_SHORTCUT="/usr/local/bin/router"

bootstrap() {
  "$SETUP_PATH/script/bootstrap"
}

setup_tools() {
  if [ -d "$SETUP_PATH/tools" ]; then
    echo "==> Setting of tools"

    for D in $SETUP_PATH/tools; do
      tool_setup="$SETUP_PATH/tools/$D/script/setup"
      if [ -d "${D}" ] && [ -f "$tool_setup" ]; then
        echo "Processing ${D}…"
        sh "$SETUP_PATH/tools/$D/script/setup"
      fi
    done
  fi
}

backup_ssh_config() {
  local config_backup
  if [ -f "$SSH_CONFIG" ]; then
    echo "==> Backing up existing configuration…" >&2
    config_backup="$(mktemp)"
    cp "$SSH_CONFIG" "$config_backup"

    echo "$config_backup"
  fi
}

remove_previous_install() {
  echo "==> Removing previous installation files…"

  if [ -f "$COMMAND_SHORTCUT" ]; then rm -rf "$COMMAND_SHORTCUT"; fi
  if [ -d "$TARGET_DIR" ]; then rm -rf "$TARGET_DIR"; fi
}

copy_install_files() {
  echo "==> Copying installation files…"
  mkdir "$TARGET_DIR"
  cp "$SETUP_PATH/router.sh" "$TARGET_DIR"
  cp -R "$SETUP_PATH/commands" "$TARGET_DIR"
  [[ -d "$SETUP_PATH/tools" ]] && cp -R "$SETUP_PATH/tools" "$TARGET_DIR"
  cp -R "$SETUP_PATH/utils" "$TARGET_DIR"
  cp -R "$SETUP_PATH/ssh" "$TARGET_DIR"
  chmod +x "$TARGET_DIR/router.sh"
  ln -s "$TARGET_DIR/router.sh" $COMMAND_SHORTCUT
}

restore_ssh_config() {
  local config_backup
  config_backup="$1"

  if [ -f "$config_backup" ]; then
    echo "==> Restoring ssh configuration…"
    cp "$config_backup" "$SSH_CONFIG"
    rm "$config_backup"
  fi
}

write_ssh_config() {
  if [ ! -f "$SSH_CONFIG" ] 2>/dev/null; then
    router writeconf
  fi
}

main() {
  local config_backup

  bootstrap
  setup_tools
  config_backup=$(backup_ssh_config)
  remove_previous_install
  copy_install_files
  restore_ssh_config "$config_backup"
  write_ssh_config

  echo "Setup done"
}

main
